### ISSUE TITLE
Swapping account for administration

### ISSUE THREAD

**Issue by wallacelab** [carpentries-incubator/microbial-amplicon-analysis#5]
@tobyhodges : I'm restructuring my lab's Github setup to separate the lab from my own work. (Part of turning the lab account into an Organization.)  As such, I need @wallacelab to be taken off this repo and @jgwall to be put in its place (as a member of the carpentries-incubator and as a maintainer for this repo (microbial-amplicon-analysis); I've already made @jgwall an admin.)

Thank you!

**Comment by tobyhodges** [comment]
I've taken care of the invitations and will come back once @jgwall has joined the Team to grant that account Maintainer privileges for the Team itself as well. Leaving this issue open until that is taken care of.

**Comment by jgwall** [comment]
Done!

**Comment by tobyhodges** [comment]
✅
